title: Max Couling
email: your-email@example.com
description: >-
  Cybersecurity Consultant & Python Developer.
baseurl: ""
url: ""

collections:
  software:
    output: true
    permalink: /software/:name/
  hardware:
    output: true
    permalink: /hardware/:name/

markdown: kramdown
theme: null

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

sass:
  style: compressed
